DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION
from .widgets import UEditorWidget, AdminUEditorWidget
from .views import get_ueditor_controller
from django.conf.urls import url

urlpatterns = [
    url(r'^controller/$', get_ueditor_controller),
]

apps/history/urls.py
from django.conf.urls import url
from django.urls import path

from . import views
from apps.history.views import MigrationRoadsView, LineageTreeView, GravesMapView

urlpatterns = [
    url(r'^migrationRoads/$', MigrationRoadsView.as_view(), name="migrationRoads"),
    url(r'^lineageTree/$', LineageTreeView.as_view(), name="lineageTree"),
    url(r'^gravesMap/$', GravesMapView.as_view(), name="gravesMap"),
]

myjiapu/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.views.static import serve

import xadmin

from apps.users.views import HomeView, LoginView, LogoutView, SignupView, SignupVerifyView
from myjiapu.settings import MEDIA_ROOT, STATIC_ROOT

urlpatterns = [
    path('xadmin/', xadmin.site.urls),
    path('', HomeView.as_view(), name="home"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('signup/', SignupView .as_view(), name="signup"),
    path('verify/', SignupVerifyView.as_view(), name="verify"),

    url(r'^history/', include(('apps.history.urls', "history"), namespace="history")),

    url(r'^captcha/', include('captcha.urls')),
    url(r'^ueditor/',include('DjangoUeditor.urls')),

    # django-auth 登录、注册、登出
    # url(r'^accounts/', include('allauth.urls')),

    # 配置上传文件的访问路径
    url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, {"document_root": STATIC_ROOT}),

    # path('admin/', admin.site.urls, name="admin"),

]

templates/gravesMap.html
<!DOCTYPE html>
<html lang="zh">

<head>
    <!-- meta -->
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=no">
    <meta name="format-detection" content="telephone=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- title -->
    <title>墓葬图-莎拉李氏</title>
    <link rel="shortcut icon" href="/static/image/favicon6.ico"/>

    <!-- css & js-->
    <link rel="shortcut icon" href="/static/image/favicon6.ico" />
    <style>
        #gravesMap {
            position: relative;
            width: 100%;
            height: 97vh;
        }
    </style>
</head>

<body>
    <div id="gravesMap"></div>

    <script type="text/javascript" src="http://api.tianditu.gov.cn/api?v=4.0&tk=c33e9c7f7892d396eec307a06d35abf4"></script>
    <script src="/static/js/gravesMap.js"></script>
</body>

</html>

templates/index.html
<!DOCTYPE html>
<html lang="jzh">
<head>
	<!-- meta -->
	<meta charset="utf-8">
	<meta name="description" content="">
	<meta name="keywords" content="">
	<meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=no">
	<meta name="format-detection" content="telephone=no">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<!-- title -->
	<title>主页-莎拉李氏</title>
	<!-- css -->
	<link rel="shortcut icon" href="/static/image/favicon6.ico"/>
	<link href="/static/css/css-Cinzel.css" rel="stylesheet">
	<link rel="stylesheet" media="all" href="/static/css/main.css">
</head>
<body class="page-top">
<div id="wrapper">
<!-- /////////////////////////////////////////////////////////////////// -->
<div class="pageCover"></div>

<header id="header" class="header">
	<div class="header__content">
		<div class="header__logoMenu">
			<h1 class="header__logo"><a href="">莎拉李氏</a></h1>
			<a href="#" class="header__menu">
				<span class="lines">
				<span class="line-1"></span>
				<span class="line-2"></span>
				<span class="line-3"></span>
				</span>
			</a>
		</div>
	</div>
	<nav class="header__nav">
		<div class="h-mainNav">
			<div class="h-mainNav__inner">
				<ul class="h-mainNav__list">
					<li><a>壹.家国观念</a></li>
					<li><a href="{% url 'history:migrationRoads' %}" target="_blank">貳.迁徙路线</a></li>
					<li><a href="{% url 'history:lineageTree' %}" target="_blank">叁.世系图</a></li>
					<li><a href="{% url 'history:gravesMap' %}" target="_blank">肆.墓葬图</a></li>
					<li><a>伍.其他余项</a></li>
				</ul>
			</div>
		</div>
		<div class="header__link">
			<ul>
                {% if request.user.is_authenticated %}
                    <li class="btn"><a href="/usercenter/" target="_blank" class="mod-btn blank">个人中心<i class="icon blank"></i></a></li>
                    <li class="btn"><a href="{% url 'logout' %}" target="_blank" class="mod-btn blank">退出<i class="icon blank"></i></a></li>
                    <li class="btn"><a href="/xadmin/" target="_blank" class="mod-btn blank">后台管理系统-实验版<i class="icon blank"></i></a></li>
                {% else %}
                    <li class="btn"><a href="{% url 'login' %}" target="_blank" class="mod-btn blank">登录<i class="icon blank"></i></a></li>
                    <li class="btn"><a href="{% url 'signup' %}" target="_blank" class="mod-btn blank">注册<i class="icon blank"></i></a></li>
                {% endif %}
			</ul>
		</div>
	</nav>
</header><!-- /#header -->

<div id="barba-wrapper">
<div class="barba-container" data-namespace="top">
	<div class="page-top">



	<div id="content" class="content">
		<div class="fv">
			<div class="fv__mainVisual">
				<div class="fv__slide">
					<div class="item slide01">
						<!--<p class="mod-cap"><span>unsplash.com 提供图</span></p>-->
						<div class="img"></div>
					</div>
					<div class="item slide02">
						<!--<p class="mod-cap"><span>unsplash.com 提供图</span></p>-->
						<div class="img"></div>
					</div>
					<div class="item slide03">
						<!--<p class="mod-cap"><span>unsplash.com 提供图</span></p>-->
						<div class="img"></div>
					</div>
					<div class="item slide04">
						<p class="mod-cap"><span>unsplash.com 提供图</span></p>
						<div class="img"></div>
					</div>
				</div>
				<div class="scroll"><span class="txt">scroll</span><span class="arw"></span></div>
			</div><!-- /.fv__mainVisual -->
		</div><!-- /.fv -->
		

		
			<div class="content__body">
				<div class="content__title easingWrap">
					<h2 class="ttl"><span class="jp">青云之志</span><span class="en">Dream</span></h2>
				</div>
				<section class="section section__wedding wedding easingWrap">
					<div class="section__body">
						<div class="section__inner">
							<p class="wedding__txt">&nbsp;&nbsp;仲夏，清风，红袖楼，青山妩媚，料我如是。北国，京园，绿萝地，十年寒夏，不回故里。</p>
							<p class="wedding__txt">&nbsp;&nbsp;迄今廿四年，所遇者皆良人，所求者皆吾愿，所爱者皆正义。辗转求学，栉风沐雨，砥砺歌行，或如琢如磨，或惟狂唯恐，冷暖自知矣。然人生于天地间，愈行愈勇，所赖者亲友、师长、贵人也，故毕业之际，敬谢诸恩于此。一谢祖国庇护英雄守护之恩，二谢父母生而教养之恩，三谢师长传道授业解惑之恩，四谢亲友扶助贵人勉励之恩。</p>
							<p class="wedding__txt">&nbsp;&nbsp;行文至此，无复再言，惟愿历经山河，不坠青云之志，不丧君子旷达之容，不失为国为民之心！</p>			
						</div>
					</div>
				</section>
			</div>

		<div class="content__inner">

			<section class="top-section intro">
				<div class="section__body">
					<div class="intro__content">
						<ul>
							<li class="chuko"><p class="title">忠孝</p><p class="ruby">Zhong</p></li>
							<li class="shisso"><p class="title">仁爱</p><p class="ruby">Ren</p></li>
							<li class="jinai"><p class="title">家国</p><p class="ruby">Jia</p></li>
						</ul>
					</div>
				</div>
			</section>
			<section class="top-section about easingWrap">
				<div class="easingFade">
					<div class="about__content">
						<div class="top-section__ttl">
							<h2 class="ttl"><span class="jp">迁徙路线</span><span class="en">Migration</span><span class="easingLine"><span class="line"></span></span></h2>
						</div>
						<div class="about__img">
							<div class="item">
								<div class="item__img easingImg easingParallax">
									<div class="img-ov">
										<img src="/static/picture/migration.png" width="2000" height="1056" alt="migration" class="pc">
										<img src="/static/picture/migration.png" width="750" height="400" alt="migration" class="sp">
									</div>
								</div>
							</div>
						</div>
						<div class="about__txt top-section__bg">
							<p class="txt">·公元1727年后，王姓支族始自云南宣威州迁至贵州大定府。宣威州即今宣威县，大定府即今毕节市及水城县等地。</p>
							<p class="txt">·公元1827年后，该支族族分两支，一支迁至马摆，一支依旧居于原属地。马摆即今锅圈岩乡青峰村、马摆一带，原属地即今放珠镇哩东村一带。迁至马摆的支族又再分三房，长房居于官寨，二房居于后槽，三方迁居于大方县。</p>
							<p class="txt">·公元1910年后，长房长支仍居于官寨，长房次支迁至董地乡田坝寨一带，长房三支迁至织金县。</p>
							<span class="line top"></span>
							<span class="line bottom"></span>
						</div>
					</div>
				</div>
			</section>
			<section class="top-section guide easingWrap">
				<div class="easingFade">
					<div class="guide__content">
						<div class="top-section__ttl">
							<h2 class="ttl"><span class="jp">世系图</span><span class="en">Descent</span><span class="easingLine"><span class="line"></span></span></h2>
						</div>
						<div class="guide__img">
							<div class="item">
								<div class="item__img easingImg easingParallax">
									<div class="img-ov">
										<img src="/static/picture/descent.png" width="2000" height="756" alt="descent" class="pc">
										<img src="/static/picture/descent.png" width="2000" height="756" alt="descent" class="sp">
									</div>
								</div>
							</div>
						</div>
						<div class="guide__txt top-section__bg">
							<p class="txt">·该世系图主要描述马摆长房世系，自我起上溯至六世祖李走则。世系图裁定日期：2020年4月14日晚。</p>
							<span class="line top"></span>
							<span class="line bottom"></span>
						</div>
					</div>
				</div>
			</section>
			<section class="top-section map easingWrap">
				<div class="easingFade">
					<div class="map__content">
						<div class="top-section__ttl">
							<h2 class="ttl"><span class="jp">墓葬图</span><span class="en">Grave</span><span class="easingLine"><span class="line"></span></span></h2>
						</div>
						<div class="map__img easingImg">
							<img src="/static/picture/grave.png" width="1140" height="1626" alt="grave">
						</div>
					</div>
				</div>
			</section>
			
			<section class="section section__wedding program easingWrap">
				<div class="section__body easingFade">
					<div class="section__inner">
						<h3 class="section__ttl">三书六礼</h3>
						<div class="program__colum2 mod-colum2">
							<ul>
								<li class="item">
									<h4 class="section__sttl">01.聘书</h4>
									<p class="item__txt">订亲之文书</p>
								</li>
								<li class="item">
									<h4 class="section__sttl">02.礼书</h4>
									<p class="item__txt">列礼之文书</p>
								</li>
								<li class="item">
									<h4 class="section__sttl">03.迎书</h4>
									<p class="item__txt">迎娶之文书</p>
								</li>
								<li class="item">
									<h4 class="section__sttl">01.纳彩</h4>
									<p class="item__txt">请媒人提亲</p>
								</li>
								<li class="item">
									<h4 class="section__sttl">02.问名</h4>
									<p class="item__txt">等待后续补充......</p>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</section>
			
			<section class="top-section access easingWrap">
				<div class="easingFade">
					<div class="access__content">
						<div class="access__ttl"><h2 class="ttl">通信地址</h2><span class="easingLineY"><span class="line"></span></span></div>
						<div class="access__map easingImg">
							<img src="/static/picture/location.png" >
						</div>
						<div class="access__address">
							<div class="address">所在地：贵州省毕节市纳雍县 553300</div>
						</div>
					</div>
				</div>
			</section>
		</div>
	</div><!-- /#content -->

	</div><!-- /.body-class -->
</div><!-- /.barba-container -->
</div><!-- /#barba-wrapper -->


<footer id="footer" class="footer">
	<div id="page-top">
		<a href="#wrapper" class="ss">
			<span class="scroll">
				<span class="txt">PAGE TOP</span>
				<span class="arw"></span>
			</span>
		</a>
	</div>
	<div class="footer__inner">
		<div class="f-logo">莎拉李氏</div>
		<p class="copyright">
			© 2019 Sariay. <a href="/xadmin/" target="_blank" class="admin">Admin</a>
		</p>
	</div>
</footer><!-- /#footer -->
</div><!-- /#wrapper -->
<!-- js -->
<script defer="" src="/static/js/main.js"></script>
<script>
    console.log("%c 模板版权属于 %c", "background: #222222; color: #ffffff", " ", "https://www.nasu-nogijinja.jp/");
</script>
</body>
</html>

templates/lineageTree.html
<!DOCTYPE html>
<html lang="zh">
<head>
    <!-- meta -->
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=no">
    <meta name="format-detection" content="telephone=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- title -->
    <title>世系图-莎拉李氏</title>
    <link rel="shortcut icon" href="/static/image/favicon6.ico"/>

    <!-- css & js-->
    <link rel="shortcut icon" href="/static/image/favicon6.ico" />
	<style type="text/css">
		#lineageTree {
			width: 100%;
			height: 150vh;
			overflow: hidden;
		}
	</style>
</head>

<body>
	<div id="lineageTree" ></div>
	<script src="/static/js/echarts.min.js" type="text/javascript" charset="utf-8"></script>
	<script src="/static/js/lineageTree.js"></script>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="zh-CN">

<head>
<meta charset="utf-8">
<title>登录-莎拉李氏</title>
    <link rel="shortcut icon" href="/static/image/favicon6.ico"/>
<link rel="stylesheet" href="/static/css/login.css">
    <style>
        .input-init {
            border-bottom: 1px solid grey;
        }
        .input-active {
            border-bottom: 1px solid green;
        }
        .input-error {
            border-bottom: 1px solid red;
        }

        .error-message{
            color: red;
            font-size: 12px;
            margin-top: 15px;
            text-align: center;
        }

        ul.errorlist{
            display: block;
            width: 100%;
            text-align: center;
            list-style: none;
            color: red;
            font-size: 12px;
        }
        .verify{
            position: relative;
        }

        .verify img {
            position: absolute;
            height: 30px;
            right: 2px;
            bottom: 2px;
        }


    </style>
</head>

<body class="login-page">
	<div class="content">
        <form action="{% url 'login' %}?redirect_to={{ next }}" method="post" autocomplete="off">
            <div class="form sign-in">
                <h2>欢迎回来</h2>
                <label>

                    <input name="username" value="{{ login_form.username.value }}" class="{% if login_form.errors.username %}input-error{% endif %}" id="username" type="text" autocomplete="off" placeholder="用户名"/>
                </label>
                <label>

                    <input name="password" value="{{ login_form.password.value }}" class="{% if login_form.errors.password %}input-error{% endif %}" id="password" type="password" autocomplete="new-password" placeholder="密码"/>
                </label>
                <p class="error-message">
                    {% if login_form.errors %}
                        {% for key, error in login_form.errors.items %}
                            {{ error }}
                        {% endfor %}
                    {% else %}
                        {{ msg }}
                    {% endif %}
                </p>
                <button type="submit"  class="submit">登 录</button>
            </div>
            {% csrf_token %}
        </form>

		<div class="sub-cont">
			<div class="img">
				<div class="img__text m--up">
					<h2>还未注册？</h2>
					<p>立即注册，发现大量机会！</p>
				</div>
				<div class="img__text m--in">
					<h2>已有帐号？</h2>
					<p>有帐号就登录吧，好久不见了！</p>
				</div>
				<div class="img__btn">
					<span class="m--up">注 册</span>
					<span class="m--in">登 录</span>
				</div>
			</div>

			<form action="{% url 'signup' %}" method="post" autocomplete="off">
                <div class="form sign-up">
                    <h2>立即注册</h2>
                    <label>
                        <input name="username" value="{{ signup_form.username.value }}" class="{% if signup_form.errors.username %}input-error{% endif %}" id="username" autocomplete="off" placeholder="用户名"/>
                    </label>
                    <label>
                        <input name="email" value="{{ signup_form.email.value }}" class="{% if signup_form.errors.email %}input-error{% endif %}" id="email" autocomplete="off" placeholder="邮箱"/>
                    </label>
                    <label>
                        <input name="password" value="{{ signup_form.password.value }}" class="{% if signup_form.errors.password %}input-error{% endif %}" id="password"  autocomplete='new-password' placeholder="密码"/>
                    </label>
                    <label>
                        <input name="password_confirm" value="{{ signup_form.password_confirm.value }}" class="{% if signup_form.errors.password %}input-error{% endif %}" id="password_confirm"  autocomplete='new-password' placeholder="密码"/>
                    </label>
                    <label name="captcha"  class= "verify {% if signup_form.errors.captcha %}verity-error{% endif %}" id="verify">
                        {{ verify_code_form.captcha }}
                    </label>
                    <p class="error-message">

                        {% if signup_form.errors %}
                            {% for key, error in signup_form.errors.items %}
                                {{ error }}
                            {% endfor %}
                        {% endif %}
                    </p>
                    <button  type="submit"  class="submit">注 册</button>

                </div>
                 {% csrf_token %}
			</form>
		</div>
	</div>
    <script>
        const PAGE_TYPE = "LOGIN";
    </script>
    <script src="/static/js/jquey-3.3.1.min.js"></script>

	<script src="/static/js/login.js"></script>
</body>

</html>

templates/migrationRoads.html
<!DOCTYPE html>
<html lang="zh">
	<head>
    <!-- meta -->
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=no">
    <meta name="format-detection" content="telephone=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- title -->
    <title>迁徙图-莎拉李氏</title>
        <link rel="shortcut icon" href="/static/image/favicon6.ico"/>

    <!-- css & js-->
    <link rel="shortcut icon" href="/static/image/favicon6.ico" />
		<style type="text/css">
			#main {
				width: 100%;
				height: 120vh;
				overflow: hidden;
			}
		</style>
	</head>
	<body>
		
		<div id="main" ></div>

		<script src="/static/js/echarts.min.js" type="text/javascript" charset="utf-8"></script>
		<script src="/static/js/china.js" type="text/javascript" charset="utf-8"></script>
		<script src="/static/js/migrationRoads.js"></script>
	</body>
</html>

templates/signup.html
<!DOCTYPE html>
<html lang="zh-CN">

<head>
<meta charset="utf-8">
<title>注册-莎拉李氏</title>
    <link rel="shortcut icon" href="/static/image/favicon6.ico"/>
<link rel="stylesheet" href="/static/css/login.css">
    <style>
        .input-init {
            border-bottom: 1px solid grey;
        }
        .input-active {
            border-bottom: 1px solid green;
        }
        .input-error {
            border-bottom: 1px solid red;
        }

        .error-message{
            color: red;
            font-size: 12px;
            margin-top: 15px;
            text-align: center;
        }

        ul.errorlist{
            display: block;
            width: 100%;
            text-align: center;
            list-style: none;
            color: red;
            font-size: 12px;
        }
        .verify{
            position: relative;
        }

        .verify img {
            position: absolute;
            height: 30px;
            right: 2px;
            bottom: 2px;
        }


    </style>
</head>

<body class="login-page">
	<div class="content">
        <form action="{% url 'login' %}?redirect_to={{ next }}" method="post" autocomplete="off">
            <div class="form sign-in">
                <h2>欢迎回来</h2>
                <label>

                    <input name="username" value="{{ login_form.username.value }}" class="{% if login_form.errors.username %}input-error{% endif %}" id="username" type="text" autocomplete="off" placeholder="用户名"/>
                </label>
                <label>

                    <input name="password" value="{{ login_form.password.value }}" class="{% if login_form.errors.password %}input-error{% endif %}" id="password" type="password" autocomplete="new-password" placeholder="密码"/>
                </label>
                <p class="error-message">
                    {% if login_form.errors %}
                        {% for key, error in login_form.errors.items %}
                            {{ error }}
                        {% endfor %}
                    {% else %}
                        {{ msg }}
                    {% endif %}
                </p>
                <button type="submit"  class="submit">登 录</button>
            </div>
            {% csrf_token %}
        </form>

		<div class="sub-cont">
			<div class="img">
				<div class="img__text m--up">
					<h2>还未注册？</h2>
					<p>立即注册，发现大量机会！</p>
				</div>
				<div class="img__text m--in">
					<h2>已有帐号？</h2>
					<p>有帐号就登录吧，好久不见了！</p>
				</div>
				<div class="img__btn">
					<span class="m--up">注 册</span>
					<span class="m--in">登 录</span>
				</div>
			</div>

			<form action="{% url 'signup' %}" method="post" autocomplete="off">
                <div class="form sign-up">
                    <h2>立即注册</h2>
                    <label>
                        <input name="username" value="{{ signup_form.username.value }}" class="{% if signup_form.errors.username %}input-error{% endif %}" id="username" autocomplete="off" placeholder="用户名"/>
                    </label>
                    <label>
                        <input name="email" value="{{ signup_form.email.value }}" class="{% if signup_form.errors.email %}input-error{% endif %}" id="email" autocomplete="off" placeholder="邮箱"/>
                    </label>
                    <label>
                        <input name="password" value="{{ signup_form.password.value }}" class="{% if signup_form.errors.password %}input-error{% endif %}" id="password"  autocomplete='new-password' placeholder="密码"/>
                    </label>
                    <label>
                        <input name="password_confirm" value="{{ signup_form.password_confirm.value }}" class="{% if signup_form.errors.password %}input-error{% endif %}" id="password_confirm"  autocomplete='new-password' placeholder="密码"/>
                    </label>
                    <label name="captcha"  class= "verify {% if signup_form.errors.captcha %}verity-error{% endif %}" id="verify">
                        {{ verify_code_form.captcha }}
                    </label>
                    <p class="error-message">

                        {% if signup_form.errors %}
                            {% for key, error in signup_form.errors.items %}
                                {{ error }}
                            {% endfor %}
                        {% endif %}
                    </p>
                    <button  type="submit"  class="submit">注 册</button>

                </div>
                 {% csrf_token %}
			</form>
		</div>
	</div>
    <script>
        const PAGE_TYPE = "SIGNUP";
    </script>
    <script src="/static/js/jquey-3.3.1.min.js"></script>

	<script src="/static/js/login.js"></script>
</body>

</html>

templates/signup_verify.html
<!DOCTYPE html>
<html lang="en" >
<head>
<meta charset="UTF-8">
<title>注册确认-莎拉李氏</title>

    <link rel="shortcut icon" href="/static/image/favicon6.ico"/>

<link href="https://fonts.googleapis.com/css?family=Righteous&display=swap" rel="stylesheet">

<link rel="stylesheet" href="/static/css/404.css">

</head>
<body>

<div class="moon"></div>
<div class="moon__crater moon__crater1"></div>
<div class="moon__crater moon__crater2"></div>
<div class="moon__crater moon__crater3"></div>

<div class="star star1"></div>
<div class="star star2"></div>
<div class="star star3"></div>
<div class="star star4"></div>
<div class="star star5"></div>

<div class="error">
  <div class="error__subtitle">Hmmm，2s后自动跳转...</div>
  <div class="error__description">{{ message }}....</div>
  <button class="error__button error__button--active"><a style="color: black; text-underline: none" href="{% url 'login' %}">返回登录</a></button>
</div>

<div class="astronaut">
  <div class="astronaut__backpack"></div>
  <div class="astronaut__body"></div>
  <div class="astronaut__body__chest"></div>
  <div class="astronaut__arm-left1"></div>
  <div class="astronaut__arm-left2"></div>
  <div class="astronaut__arm-right1"></div>
  <div class="astronaut__arm-right2"></div>
  <div class="astronaut__arm-thumb-left"></div>
  <div class="astronaut__arm-thumb-right"></div>
  <div class="astronaut__leg-left"></div>
  <div class="astronaut__leg-right"></div>
  <div class="astronaut__foot-left"></div>
  <div class="astronaut__foot-right"></div>
  <div class="astronaut__wrist-left"></div>
  <div class="astronaut__wrist-right"></div>

  <div class="astronaut__cord">
    <canvas id="cord" height="500px" width="500px"></canvas>
  </div>

  <div class="astronaut__head">
    <canvas id="visor" width="60px" height="60px"></canvas>
    <div class="astronaut__head-visor-flare1"></div>
    <div class="astronaut__head-visor-flare2"></div>
  </div>
</div>

<script  src="/static/js/404.js"></script>
<script>
    window.setTimeout("window.location='/login/'",2000);
</script>
</body>
</html>